import { lazy, type ComponentType, type LazyExoticComponent } from 'react'
import type { GameMeta, IslandDef, IslandId } from '@/engine/types'

// ============================================================
// LA source unique de vérité : génère le hub, les routes,
// et la carte de compétences du dashboard parent.
// Ajouter un jeu = ajouter une entrée ici (+ dossier src/games/<id>).
// ============================================================

export const ISLANDS: IslandDef[] = [
  {
    id: 'sons',
    name: 'L’Île aux Sons',
    emoji: '🔊',
    tagline: 'Lire, écouter, écrire',
    accent: '#ff7866',
  },
  {
    id: 'nombres',
    name: 'L’Île aux Nombres',
    emoji: '🔢',
    tagline: 'Compter, calculer, payer',
    accent: '#5ab8f5',
  },
  {
    id: 'robots',
    name: 'L’Île des Robots',
    emoji: '🤖',
    tagline: 'Logique et petits programmes',
    accent: '#58c472',
  },
  {
    id: 'monde',
    name: 'L’Île du Monde',
    emoji: '🌋',
    tagline: 'Le temps, l’espace, la nature',
    accent: '#ffc94d',
  },
  {
    id: 'ailleurs',
    name: 'L’Île d’Ailleurs',
    emoji: '🛶',
    tagline: 'English, musique et couleurs',
    accent: '#9b7ede',
  },
  {
    id: 'sentiments',
    name: 'L’Île des Sentiments',
    emoji: '💛',
    tagline: 'Les émotions et les autres',
    accent: '#ef6f9c',
  },
]

export const ISLANDS_BY_ID: ReadonlyMap<IslandId, IslandDef> = new Map(
  ISLANDS.map((i) => [i.id, i]),
)

// ---------- Jeux V2 (lazy chunks) ----------
export const V2_COMPONENTS: Record<string, LazyExoticComponent<ComponentType>> = {
  'robo-pilote': lazy(() => import('@/games/robo-pilote')),
  'train-des-syllabes': lazy(() => import('@/games/train-des-syllabes')),
  'gloutons-du-dix': lazy(() => import('@/games/gloutons-du-dix')),
  'fabrique-de-nombres': lazy(() => import('@/games/fabrique-de-nombres')),
  'machine-a-ecrire': lazy(() => import('@/games/machine-a-ecrire')),
  'ptit-marchand': lazy(() => import('@/games/ptit-marchand')),
  // ---- Phase 2 : vague français/maths ----
  'chasse-aux-lettres': lazy(() => import('@/games/chasse-aux-lettres')),
  'machine-folle': lazy(() => import('@/games/machine-folle')),
  'bar-a-schemas': lazy(() => import('@/games/bar-a-schemas')),
  'calcul-aventure': lazy(() => import('@/games/calcul-aventure')),
  'balance-magique': lazy(() => import('@/games/balance-magique')),
  'riviere-aux-lucioles': lazy(() => import('@/games/riviere-aux-lucioles')),
  'boites-a-nombres': lazy(() => import('@/games/boites-a-nombres')),
  // ---- Phase 3 : les mondes ----
  'grand-horloger': lazy(() => import('@/games/grand-horloger')),
  'collier-de-perles': lazy(() => import('@/games/collier-de-perles')),
  'atelier-pixel': lazy(() => import('@/games/atelier-pixel')),
  'mysteres-au-village': lazy(() => import('@/games/mysteres-au-village')),
  'mots-de-la-semaine': lazy(() => import('@/games/mots-de-la-semaine')),
  'english-island': lazy(() => import('@/games/english-island')),
  'laboratoire-eau': lazy(() => import('@/games/laboratoire-eau')),
  'orchestre-des-animaux': lazy(() => import('@/games/orchestre-des-animaux')),
  // ---- Phase 4 : ouverture et CE1 ----
  'fluence-express': lazy(() => import('@/games/fluence-express')),
  'lettre-magique': lazy(() => import('@/games/lettre-magique')),
  'pizzeria-des-fractions': lazy(() => import('@/games/pizzeria-des-fractions')),
  // ---- Phase 5 : remplacement des jeux classiques V1 ----
  'cantine-foret': lazy(() => import('@/games/cantine-foret')),
  'atelier-couleurs': lazy(() => import('@/games/atelier-couleurs')),
  'carre-magique': lazy(() => import('@/games/carre-magique')),
  'ecole-plume': lazy(() => import('@/games/ecole-plume')),
  'jardin-emotions': lazy(() => import('@/games/jardin-emotions')),
  // ---- Sprint conformité 2026-2027 : nouveaux programmes au CP ----
  'corps-humain': lazy(() => import('@/games/corps-humain')),
  'petite-graine': lazy(() => import('@/games/petite-graine')),
  'atelier-objets': lazy(() => import('@/games/atelier-objets')),
  'machine-du-temps': lazy(() => import('@/games/machine-du-temps')),
  'tour-du-monde': lazy(() => import('@/games/tour-du-monde')),
  'hello-friends': lazy(() => import('@/games/hello-friends')),
  'my-body-food': lazy(() => import('@/games/my-body-food')),
  'atelier-formes': lazy(() => import('@/games/atelier-formes')),
  'metre-magique': lazy(() => import('@/games/metre-magique')),
  'regles-du-village': lazy(() => import('@/games/regles-du-village')),
}

export const GAMES: GameMeta[] = [
  // ======================= JEUX V2 =======================
  {
    id: 'robo-pilote',
    title: 'Robo-Pilote',
    tagline: 'Programme le robot jusqu’au trésor !',
    icon: '🤖',
    island: 'robots',
    accent: '#00897b',
    skills: ['lo.gs.directions', 'lo.cp.code.sequence', 'lo.cp.code.boucles'],
    status: 'v2',
  },
  {
    id: 'train-des-syllabes',
    title: 'Le Train des Syllabes',
    tagline: 'Écoute le mot, assemble les wagons !',
    icon: '🚂',
    island: 'sons',
    accent: '#2e7d32',
    skills: [
      'fr.gs.phono.scander',
      'fr.gs.phono.fusion',
      'fr.gs.phono.suppression',
      'fr.cp.decodage.syllabes',
    ],
    status: 'v2',
  },
  {
    id: 'gloutons-du-dix',
    title: 'Les Gloutons du Dix',
    tagline: 'Nourris les gloutons avec le bon compte !',
    icon: '🪄',
    island: 'nombres',
    accent: '#7e57c2',
    skills: ['ma.gs.decompo5', 'ma.gs.decompo10', 'ma.cp.complements10', 'ma.cp.doubles'],
    status: 'v2',
  },
  {
    id: 'fabrique-de-nombres',
    title: 'La Fabrique de Nombres',
    tagline: 'Fabrique les nombres avec barres et cubes !',
    icon: '🏗️',
    island: 'nombres',
    accent: '#1565c0',
    skills: [
      'ma.cp.num.lire59',
      'ma.cp.num.dizaines',
      'ma.cp.num.echange',
      'ma.cp.num.decompo100',
    ],
    status: 'v2',
  },
  {
    id: 'machine-a-ecrire',
    title: 'La Machine à Écrire Magique',
    tagline: 'Écoute le son, écris-le avec les touches !',
    icon: '⌨️',
    island: 'sons',
    accent: '#ad1457',
    skills: [
      'fr.cp.cgp.voyelles',
      'fr.cp.cgp.consonnes1',
      'fr.cp.cgp.digraphes1',
      'fr.cp.encodage.syllabes',
      'fr.cp.encodage.mots',
    ],
    status: 'v2',
  },
  {
    id: 'ptit-marchand',
    title: 'Le P’tit Marchand',
    tagline: 'Sers les clients et rends la monnaie !',
    icon: '🏪',
    island: 'nombres',
    accent: '#f9a825',
    skills: ['ma.cp.monnaie.pieces', 'ma.cp.monnaie.payer', 'ma.cp.monnaie.rendre', 'ma.cp.add10'],
    status: 'v2',
  },

  // ============= JEUX V2 — PHASE 2 (vague français/maths) =============
  {
    id: 'chasse-aux-lettres',
    title: 'La Chasse aux Lettres',
    tagline: 'Écoute la lettre, attrape-la dans la scène !',
    icon: '🔎',
    island: 'sons',
    accent: '#e74c3c',
    skills: [
      'fr.gs.lettres.nom',
      'fr.gs.lettres.graphies',
      'fr.gs.phono.attaque',
      'fr.cp.lettres.confusables',
    ],
    status: 'v2',
  },
  {
    id: 'machine-folle',
    title: 'La Machine Folle',
    tagline: 'Tourne les rouleaux, répare la phrase !',
    icon: '🎰',
    island: 'sons',
    accent: '#e65100',
    skills: ['fr.cp.phrase.sens', 'fr.cp.phrase.accord-gn', 'fr.cp.phrase.accord-sv'],
    status: 'v2',
  },
  {
    id: 'bar-a-schemas',
    title: 'Le Bar à Schémas',
    tagline: 'Écoute l’histoire, dessine le problème !',
    icon: '📊',
    island: 'nombres',
    accent: '#00796b',
    skills: ['ma.cp.pb.partiestout', 'ma.cp.pb.transfo', 'ma.cp.pb.partie', 'ma.cp.pb.compare'],
    status: 'v2',
  },
  {
    id: 'calcul-aventure',
    title: 'Calcul Aventure',
    tagline: 'Remplis le panier et tape le résultat !',
    icon: '🗺️',
    island: 'nombres',
    accent: '#3498db',
    skills: ['ma.cp.add10', 'ma.cp.sous10', 'ma.cp.add20', 'ma.cp.sous20'],
    status: 'v2',
  },
  {
    id: 'balance-magique',
    title: 'La Balance Magique',
    tagline: 'Équilibre les plateaux du magicien !',
    icon: '⚖️',
    island: 'nombres',
    accent: '#8e44ad',
    skills: ['ma.gs.comparer', 'ma.cp.complements10', 'ma.cp.egalite', 'ma.cp.num.echange'],
    status: 'v2',
  },
  {
    id: 'riviere-aux-lucioles',
    title: 'La Rivière aux Lucioles',
    tagline: 'Pose la luciole au bon endroit !',
    icon: '✨',
    island: 'nombres',
    accent: '#00acc1',
    skills: ['ma.gs.droite10', 'ma.cp.num.droite'],
    status: 'v2',
  },
  {
    id: 'boites-a-nombres',
    title: 'Les Boîtes à Nombres',
    tagline: 'Remplis les boîtes, ferme, expédie !',
    icon: '📦',
    island: 'nombres',
    accent: '#8d6e63',
    skills: ['ma.gs.subitizing', 'ma.gs.denombrer10', 'ma.gs.comparer'],
    status: 'v2',
  },

  // ============= JEUX V2 — PHASE 3 (les mondes) =============
  {
    id: 'grand-horloger',
    title: 'Le Grand Horloger',
    tagline: 'Règle les aiguilles, fais tourner le temps !',
    icon: '🕰️',
    island: 'monde',
    accent: '#9b59b6',
    skills: ['mo.gs.temps.journee', 'mo.gs.temps.semaine', 'mo.cp.temps.heures', 'mo.cp.temps.calendrier'],
    status: 'v2',
  },
  {
    id: 'collier-de-perles',
    title: 'Le Collier de Perles',
    tagline: 'Pose les perles, continue le motif !',
    icon: '📿',
    island: 'robots',
    accent: '#5c6bc0',
    skills: ['lo.gs.motifs.suite', 'lo.gs.motifs.creer'],
    status: 'v2',
  },
  {
    id: 'atelier-pixel',
    title: 'L’Atelier Pixel',
    tagline: 'Copie, miroir, mémoire… peins les pixels !',
    icon: '🎨',
    island: 'robots',
    accent: '#4527a0',
    skills: ['lo.gs.quadrillage', 'lo.cp.coordonnees', 'lo.cp.symetrie'],
    status: 'v2',
  },
  {
    id: 'mysteres-au-village',
    title: 'Mystères au Village',
    tagline: 'Écoute l’histoire, démasque le personnage !',
    icon: '🕵️',
    island: 'sons',
    accent: '#1b5e20',
    skills: ['fr.cp.comp.anaphores', 'fr.cp.comp.inferences'],
    status: 'v2',
  },
  {
    id: 'mots-de-la-semaine',
    title: 'Les Mots de la Semaine',
    tagline: 'Explore l’imagier, attrape les mots !',
    icon: '📖',
    island: 'sons',
    accent: '#00bcd4',
    skills: ['fr.gs.vocab.mots', 'fr.gs.vocab.categories'],
    status: 'v2',
  },
  {
    id: 'english-island',
    title: 'English Island',
    tagline: 'Colours, numbers, animals… in English!',
    icon: '🏝️',
    island: 'ailleurs',
    accent: '#1565c0',
    skills: ['en.cp.colours', 'en.cp.numbers', 'en.cp.animals', 'en.cp.consignes'],
    status: 'v2',
  },
  {
    id: 'laboratoire-eau',
    title: 'Le Laboratoire de l’Eau',
    tagline: 'Chauffe, gèle, fais voyager la goutte !',
    icon: '💧',
    island: 'monde',
    accent: '#0277bd',
    skills: ['mo.gs.eau.etats', 'mo.cp.eau.cycle'],
    status: 'v2',
  },
  {
    id: 'orchestre-des-animaux',
    title: 'L’Orchestre des Animaux',
    tagline: 'Écoute, rejoue, compose ta musique !',
    icon: '🎵',
    island: 'ailleurs',
    accent: '#4a148c',
    skills: ['ar.gs.rythme.reproduire', 'ar.gs.rythme.composer'],
    status: 'v2',
  },

  // ============= JEUX V2 — PHASE 4 (ouverture et CE1) =============
  {
    id: 'fluence-express',
    title: 'Fluence Express',
    tagline: 'Lis vite et bien, le train accélère !',
    icon: '🚄',
    island: 'sons',
    accent: '#c62828',
    skills: ['fr.cp.fluence', 'fr.ce1.fluence'],
    status: 'v2',
  },
  {
    id: 'lettre-magique',
    title: 'La Lettre Magique',
    tagline: 'Trace les lettres avec ton doigt !',
    icon: '✍️',
    island: 'sons',
    accent: '#6d4c41',
    skills: ['fr.gs.graphisme.formes', 'fr.cp.ecriture.cursive'],
    status: 'v2',
  },
  {
    id: 'pizzeria-des-fractions',
    title: 'La Pizzeria des Fractions',
    tagline: 'Coupe, partage, sers les parts égales !',
    icon: '🍕',
    island: 'nombres',
    accent: '#d84315',
    skills: ['ma.ce1.fractions.parts', 'ma.ce1.fractions.lire'],
    status: 'v2',
  },

  // ============= JEUX V2 — PHASE 5 (remplacement des classiques V1) =============
  {
    id: 'cantine-foret',
    title: 'La Cantine de la Forêt',
    tagline: 'Sers le bon repas à chaque animal !',
    icon: '🍽️',
    island: 'monde',
    accent: '#2e9e5b',
    skills: ['mo.gs.vivant.regime', 'mo.cp.vivant.classer'],
    status: 'v2',
  },
  {
    id: 'atelier-couleurs',
    title: 'L’Atelier des Couleurs',
    tagline: 'Mélange les peintures et trouve la bonne couleur !',
    icon: '🎨',
    island: 'ailleurs',
    accent: '#d81b60',
    skills: ['ar.gs.couleurs.primaires', 'ar.gs.couleurs.melanges', 'ar.cp.couleurs.obtenir'],
    status: 'v2',
  },
  {
    id: 'carre-magique',
    title: 'La Grille des Robots',
    tagline: 'Un seul robot par ligne, par colonne et par carré !',
    icon: '🧩',
    island: 'robots',
    accent: '#5c6bc0',
    skills: ['lo.gs.quadrillage', 'lo.gs.deduction.contrainte'],
    status: 'v2',
  },
  {
    id: 'ecole-plume',
    title: 'L’École de Plume',
    tagline: 'Guide Plume dans toute l’école !',
    icon: '🗺️',
    island: 'monde',
    accent: '#43a047',
    skills: ['mo.gs.espace.reperer', 'mo.cp.espace.itineraire'],
    status: 'v2',
  },
  {
    id: 'jardin-emotions',
    title: 'Le Jardin des Émotions',
    tagline: 'Reconnais les émotions et fais fleurir le jardin !',
    icon: '🌸',
    island: 'sentiments',
    accent: '#ef6f9c',
    skills: ['emc.gs.emotions.nommer', 'emc.cp.emotions.reconnaitre', 'emc.cp.conflit.reguler'],
    status: 'v2',
  },

  // ============= JEUX V2 — SPRINT CONFORMITÉ 2026-2027 =============
  // Nouveaux programmes au CP (sciences-techno BO 06/2026, histoire-géo
  // BO 05/2026), anglais Pré-A1 (BO 03/2026), géométrie & mesures
  // (BO oct. 2024), EMC. Habillage emoji (fallback), V3 illustré plus tard.
  {
    id: 'corps-humain',
    title: 'Le Corps Humain',
    tagline: 'Écoute et trouve la bonne partie du corps !',
    icon: '🧍',
    island: 'monde',
    accent: '#e8743b',
    skills: ['mo.gs.corps.parties', 'mo.cp.corps.sens', 'mo.cp.corps.hygiene'],
    status: 'v2',
  },
  {
    id: 'petite-graine',
    title: 'La Petite Graine',
    tagline: 'Donne-lui ce qu’il faut et fais pousser la plante !',
    icon: '🌱',
    island: 'monde',
    accent: '#7cb342',
    skills: ['mo.gs.vivant.besoins', 'mo.cp.vivant.cycle'],
    status: 'v2',
  },
  {
    id: 'atelier-objets',
    title: 'L’Atelier des Objets',
    tagline: 'Un objet pour chaque besoin, une matière pour chaque objet !',
    icon: '🔧',
    island: 'monde',
    accent: '#a1887f',
    skills: ['mo.cp.objets.besoin', 'mo.cp.objets.matiere'],
    status: 'v2',
  },
  {
    id: 'machine-du-temps',
    title: 'La Machine à Remonter le Temps',
    tagline: 'Autrefois ou aujourd’hui ? Range le temps !',
    icon: '⏳',
    island: 'monde',
    accent: '#a98467',
    skills: ['mo.cp.histoire.avant', 'mo.cp.histoire.generations'],
    status: 'v2',
  },
  {
    id: 'tour-du-monde',
    title: 'Le Tour du Monde',
    tagline: 'Reconnais les paysages et explore la Terre !',
    icon: '🌍',
    island: 'monde',
    accent: '#2196f3',
    skills: ['mo.gs.geo.paysages', 'mo.cp.geo.monde'],
    status: 'v2',
  },
  {
    id: 'hello-friends',
    title: 'Hello Friends!',
    tagline: 'Salue, présente-toi et dis comment tu te sens, in English!',
    icon: '👋',
    island: 'ailleurs',
    accent: '#ff7043',
    skills: ['en.cp.greetings', 'en.cp.self', 'en.cp.feelings'],
    status: 'v2',
  },
  {
    id: 'my-body-food',
    title: 'My Body & Food',
    tagline: 'Head, shoulders… and yummy food, in English!',
    icon: '🍎',
    island: 'ailleurs',
    accent: '#e53935',
    skills: ['en.cp.body', 'en.cp.food', 'en.cp.tastes'],
    status: 'v2',
  },
  {
    id: 'atelier-formes',
    title: 'L’Atelier des Formes',
    tagline: 'Reconnais les formes et les solides !',
    icon: '🔷',
    island: 'nombres',
    accent: '#3949ab',
    skills: ['ma.gs.geo.formes', 'ma.cp.geo.solides'],
    status: 'v2',
  },
  {
    id: 'metre-magique',
    title: 'Le Mètre Magique',
    tagline: 'Plus long, plus court… mesure tout !',
    icon: '📏',
    island: 'nombres',
    accent: '#0097a7',
    skills: ['ma.gs.mesure.comparer', 'ma.cp.mesure.longueurs'],
    status: 'v2',
  },
  {
    id: 'regles-du-village',
    title: 'Les Règles du Village',
    tagline: 'Choisis ce qui aide et respecte les autres !',
    icon: '🤝',
    island: 'sentiments',
    accent: '#f06292',
    skills: ['emc.cp.regles', 'emc.cp.entraide'],
    status: 'v2',
  },

  // ==================== JEUX CLASSIQUES (V1) ====================
  // Phase 5 terminée : les 5 derniers jeux V1 ont été remplacés par des jeux
  // V2 conformes (cantine-foret, atelier-couleurs, carre-magique, ecole-plume,
  // jardin-emotions). Plus aucun jeu « classique » exposé dans le hub.
  // Les pages public/v1/*.html restent dans le dépôt (historique), non liées.
]

export const GAMES_BY_ID: ReadonlyMap<string, GameMeta> = new Map(GAMES.map((g) => [g.id, g]))

export const V2_GAMES = GAMES.filter((g) => g.status === 'v2')
export const CLASSIC_GAMES = GAMES.filter((g) => g.status === 'classique')
